# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mburia', '0002_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Mburia_question',
        ),
    ]
