# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 11:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mburia', '0003_auto_20170714_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mburia_answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('date_answered', models.DateTimeField(auto_now_add=True)),
                ('answer_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mburia.Mburia_question')),
            ],
        ),
    ]
