# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mburia', '0004_mburia_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer_vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(max_length=20)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mburia.Mburia_answer')),
                ('voting_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
